version: '3'
services:
  apache:
    build:
      args:
        PHP_VER: $PHP_VER
      context: .
      dockerfile: ./apache.DockerFile
    ports:
      - '$APACHE_PORT:80'
      - '$APACHE_SSL_PORT:443'
      - '$XDEBUG_PORT'
    environment:
      ## APACHE ##
      - APACHE_SERVER_NAME=$APACHE_HOST:$APACHE_PORT
      - APACHE_LOG_DIR=/etc/apache2/log
      - APACHE_SERVER_PORT=80
    volumes:
      - './../:/var/www/html'
      - './ssl:/etc/apache2/ssl/'
      - './logs:/etc/apache2/log'
      - './000-default.conf:/etc/apache2/sites-available/000-default.conf'
